Repository DBG-Afelio/JS_fullstack_2020, pull requests merged in 2020-05, with the labels that each got.

#418 BenoitMayeur-logique-ex4b2
  stagiaires/benoit/exercices/logique/ex4b2.txt
Labels: CHAP4 - BOUCLES, PSEUDOCODE

#475 BenoitMayeur-ex6.4
  stagiaires/benoit/exercices/logique/ex6.4.txt
Labels: CHAP6 - VECTEURS, PSEUDOCODE

#473 Exoflo6.5
  stagiaires/florent/exercices/Logique/Exo 6.5 - Suppression des espaces
Labels: CHAP6 - VECTEURS, PSEUDOCODE

#467 PC logique-6-5b
  stagiaires/pierrecast/exercices/logique/6.5.txt
  stagiaires/pierrecast/exercices/logique/6.5b.txt
Labels: CHAP6 - VECTEURS, PSEUDOCODE

#288 add ex 3.3
  stagiaires/thomas/logique-progra/boolean/partie-3-alternative-pseudocode/exercice-3.3.txt
Labels: CHAP3 - ALTERNATIVES, PSEUDOCODE

#323 Logique boucles ex 4.2
  stagiaires/thomas/logique-progra/boucles/exercice-4.2.txt
  stagiaires/thomas/logique-progra/partie-3-alternative-pseudocode/exercice-3.1.txt
  stagiaires/thomas/logique-progra/partie-3-alternative-pseudocode/exercice-3.2.txt
Labels: CHAP4 - BOUCLES, PSEUDOCODE

#474 add ex-6.3
  stagiaires/thomas/logique-progra/vecteurs/exercice-6.3.txt
Labels: CHAP6 - VECTEURS, PSEUDOCODE

#262 logique boolean ex 2.12
  stagiaires/thomas/logique-progra/boolean/exercice-boolean-2.12.txt
Labels: CHAP2 - BOOLEENS, PSEUDOCODE

#442 Ajout exo 6.2
  stagiaires/oshi/Logique/Exo-6.2-Min-max-vecteur.txt
Labels: CHAP6 - VECTEURS, PSEUDOCODE

#484 exe 6.5
  stagiaires/jerome/exercices/Logique/exe 6.5.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#477 feature/assia/logique/vecteurs/ex6.5
  stagiaires/assia/exercices/logique-programmation/ex6.5.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#448 Ajout exo 6.5
  stagiaires/oshi/Logique/Exo-6.5-Supprimer-espaces.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#452 Ajout exo 6.6
  stagiaires/oshi/Logique/Exo-6.6-Copie-plus-ou-moins.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#457 PC logique-6-6
  stagiaires/pierrecast/exercices/logique/6.6.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#466 Exoflo6.4
  stagiaires/florent/exercices/Logique/Exo 6.4 - Inversion vecteur
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#468 Ex6.5
  stagiaires/benoit/exercices/logique/ex6.5.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#478 feature/assia/logique/vecteurs/6.6
  stagiaires/assia/exercices/logique-programmation/ex6.6.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#485 exe 6.6
  stagiaires/jerome/exercices/Logique/exe 6.6.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#491 Exo 6.6
  stagiaires/florent/exercices/Logique/Exo 6.6
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#483 Correction 6.4
  stagiaires/thomas/logique-progra/vecteurs/exercice-6.4.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#471 Logique ex6.6
  stagiaires/benoit/exercices/logique/ex6.6.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#492 Feature/assia/logique/vecteurs/6.7
  stagiaires/assia/exercices/logique-programmation/ex6.7.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#493 add ex-6.6
  stagiaires/thomas/logique-progra/vecteurs/exercice-6.6.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#445 6.2
  stagiaires/haroon/exercices/logique/6.2.txt
  stagiaires/haroon/exercices/logique/6.3.txt
  stagiaires/haroon/exercices/logique/6.4.txt
  stagiaires/haroon/exercices/logique/6.5.txt
  stagiaires/haroon/exercices/logique/6.6.txt
  stagiaires/haroon/exercices/logique/6.7.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#459 PC logique-6-7
  stagiaires/pierrecast/exercices/logique/6.7.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#495 exe 6.7
  stagiaires/jerome/exercices/Logique/exe 6.7.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#400 Feature/assia/code js/1.5b circonference
  stagiaires/assia/exercices/sprint1_JS/1.5b-Circonference/consigne.txt
  stagiaires/assia/exercices/sprint1_JS/1.5b-Circonference/home.html
  stagiaires/assia/exercices/sprint1_JS/1.5b-Circonference/script.js
  stagiaires/assia/exercices/sprint1_JS/1.5b-Circonference/style.css
Labels: ***CODE***, CHAP1 - VAR. & AFFICHAGE

#472 Ex 6.7
  stagiaires/benoit/exercices/logique/ex6.7.txt
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#502 Feature/assia/sprint2/7.1
  stagiaires/assia/exercices/logique-programmation/ex7.1.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#503 exe 7.1
  stagiaires/jerome/exercices/Logique/exe 7.1.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#506 Ajout Exo 7.1
  stagiaires/oshi/Logique/Exo-7.1-Diagonale-dun-carre.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#504 Exoflo7.1
  stagiaires/florent/exercices/Logique/Exo 7.1 - Diagonale d'un tableau
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#507 7.2.1-avec 3 variables
  stagiaires/assia/exercices/logique-programmation/ex7.2.1.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#513 BenoitMayeur-logique-ex7.1
  stagiaires/benoit/exercices/logique/ex7.1.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#514 ex7.3
  stagiaires/assia/exercices/logique-programmation/7.3.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#518 exe 7.2
  stagiaires/jerome/exercices/Logique/exe 7.2.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#508 PC logique-7-2
  stagiaires/pierrecast/exercices/logique/7.2.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#523 exe 7.3
  stagiaires/jerome/exercices/Logique/exe 7.3.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#511 PC logique-7-3
  stagiaires/pierrecast/exercices/logique/7.3.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#520 Exoflo7.2
  stagiaires/florent/exercices/Logique/Exo 7.2 - Copie Tableau
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#526 ex7.4
  stagiaires/assia/exercices/logique-programmation/ex7.4.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#524 Exoflo7.3
  stagiaires/florent/exercices/Logique/Exo7.3 - Moyenne, Min et Max par ligne
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#413 Exoflo5.5
  stagiaires/florent/exercices/Logique/Exo 5.5 - Plus Grand
Labels: ***PSEUDOCODE***, CHAP5 - TEXTE

#516 PC logique-7-4
  stagiaires/pierrecast/exercices/logique/7.4.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#528 Logique-ex5.5
  stagiaires/benoit/exercices/logique/ex5.4.txt
  stagiaires/benoit/exercices/logique/ex5.5.txt
Labels: ***PSEUDOCODE***, CHAP5 - TEXTE

#487 Logique - ex5.3
  stagiaires/benoit/exercices/logique/ex5.3.txt
Labels: ***PSEUDOCODE***, CHAP5 - TEXTE

#522 Ajout Exo 7.2b
  stagiaires/oshi/Logique/Exo-7.2b-Copie-tableau.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#534 Exoflo7.4
  stagiaires/florent/exercices/Logique/Exo 7.4 - Carré magique
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#536 BenoitMayeur-logique-ex7.2b
  stagiaires/benoit/exercices/logique/ex7.2B.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#537 BenoitMayeur-logique-ex7.3b
  stagiaires/benoit/exercices/logique/ex7.3.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#545 exe 7.4
  stagiaires/jerome/exercices/Logique/exe 7.4.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#544 Logique - Ex 7.5
  stagiaires/benoit/exercices/logique/ex7.5.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#546 Feature/pierre cast/logique 8 1
  stagiaires/pierrecast/exercices/logique/8.1.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#549 Exoflo8.1
  stagiaires/florent/exercices/Logique/Exo 8.1 - Table de multiplication
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#555 Ajout Exo 8.1
  stagiaires/oshi/Logique/Exo-8.1-Multiplication.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#550 ex8.1
  stagiaires/assia/exercices/logique-programmation/ex8.1.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#552 exe 8.1
  stagiaires/jerome/exercices/Logique/exe 8.1.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#563 Ajout Exo 8.2
  stagiaires/oshi/Logique/Exo-8.2-Compteur-digital.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#547 Feature/pierre cast/logique 8 2
  stagiaires/pierrecast/exercices/logique/8.2.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#553 Exoflo8.3
  stagiaires/florent/exercices/Logique/Exo 8.3 - Nbre parfait
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#548 Feature/pierre cast/logique 8 3
  stagiaires/pierrecast/exercices/logique/8.3.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#559 exe 8.3
  stagiaires/jerome/exercices/Logique/exe 8.3.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#558 8.2 version simple avec longueur et concat
  stagiaires/assia/exercices/logique-programmation/ex8.2.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#554 Feature/logic/8.2
  stagiaires/jerome/exercices/Logique/exe 8.2.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#561 8.2
  stagiaires/pierrep/exercices/Logique/8.2.999
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#556 Feature/pierrecast/logique 8 4
  stagiaires/pierrecast/exercices/logique/8.4.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#494 Exoflo6.7
  stagiaires/florent/exercices/Logique/Exo 6.7 - somme des suivants
Labels: ***PSEUDOCODE***, CHAP6 - VECTEURS

#344 PC logique-4-4
  stagiaires/pierrecast/exercices/logique/4.4.txt
Labels: ***PSEUDOCODE***, CHAP4 - BOUCLES

#567 BenoitMayeur-logique-ex8.1
  stagiaires/benoit/exercices/logique/ex8.1.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#570 ex8.4
  stagiaires/assia/exercices/logique-programmation/ex8.4.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#551 Exoflo8.2
  stagiaires/florent/exercices/Logique/Exo 8.2 - Compteur digital
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#572 BenoitMayeur-logique-8.2
  stagiaires/benoit/exercices/logique/ex8.2.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#577 Ajout Exo 8.4
  stagiaires/oshi/Logique/Exo-8.4-Nombres-premier.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#562 8.1
  stagiaires/pierrep/exercices/Logique/8.1.Multiplications
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#557 Exoflo8.4
  stagiaires/florent/exercices/Logique/Exo 8.4 - Nbre premier
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#565 ex8.3
  stagiaires/assia/exercices/logique-programmation/ex8.3.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#582 ex10.1 ex1
  stagiaires/assia/exercices/logique-programmation/ex10.1.1.txt
Labels: ***PSEUDOCODE***, CHAP10 - STRUCTURES, CHAP9 - FONCTIONS

#583 PC logique 10-1a
  stagiaires/pierrecast/exercices/logique/10.1a.txt
Labels: ***PSEUDOCODE***, CHAP10 - STRUCTURES, CHAP9 - FONCTIONS

#289 3.3. pierrep
  stagiaires/pierrep/exercices/Logique/3.3. Décomposition d'une somme d'argent
Labels: ***PSEUDOCODE***, CHAP3 - ALTERNATIVES

#573 Ajout Exo 8.3
  stagiaires/oshi/Logique/Exo-8.3-Nombre-parfait.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#564 8.3
  stagiaires/pierrep/exercices/Logique/8.3.Parfaits
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#497 BenoitMayeur-logique-ex5.6
  stagiaires/benoit/exercices/logique/ex5.6.txt
Labels: ***PSEUDOCODE***, CHAP5 - TEXTE

#538 BenoitMayeur-logique-ex7.4
  stagiaires/benoit/exercices/logique/ex7.4.txt
Labels: ***PSEUDOCODE***, CHAP7 - VECTEURS - Tableaux 2D

#578 BenoitMayeur-logique-ex8.3
  stagiaires/benoit/exercices/logique/ex8.3.txt
Labels: ***PSEUDOCODE***, CHAP8 - BOUCLES IMBRIQUEES

#498 BenoitMayeur-logique-ex5.7
  stagiaires/benoit/exercices/logique/ex5.7.txt
Labels: ***PSEUDOCODE***, CHAP5 - TEXTE

#499 BenoitMayeur-logique-ex5.8
  stagiaires/benoit/exercices/logique/ex5.8.txt
Labels: ***PSEUDOCODE***, CHAP5 - TEXTE

#540 BenoitMayeur-Formulaire-HTML
  stagiaires/benoit/exercices/html-validation/Enoncé.png
  stagiaires/benoit/exercices/html-validation/README.md
  stagiaires/benoit/exercices/html-validation/css/screen.css
  stagiaires/benoit/exercices/html-validation/index.html
Labels: ***CODE***, CSS, HTML
